### ISSUE TITLE
Compiled-CloudVolumeParticle.shader cashes my game on early loading

### ISSUE THREAD

**Issue by RealKolago** [Nhawks1717/StockVisualEnhancements#2]
If I remove GameData\EnvironmentalVisualEnhancements\Shaders\Compiled-CloudVolumeParticle.shader the game starts.

Running Win64 and [KSP Version]: 1.1.0.1230 (WindowsPlayer) (x64) 
Args: KSP_x64.exe -popupwindow -force-d3d11

Log: https://www.dropbox.com/s/44s35lb8llbekt5/output_log_14.zip?dl=0

**Comment by Nhawks1717** [comment]
Switch to using DirectX 9, 11 is super buggy right now

**Comment by RealKolago** [comment]
I hope DirectX 11 gets fixed soon.

**Comment by Nhawks1717** [comment]
That's an issue with KSP, not SVE :)
